name: Reusable workflow
on:
  workflow_call:
    inputs:
      username:
        default: 'world'
        required: true
        type: string
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello ${{ inputs.who-to-greet }}"
      - name: setting time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
        
        
